Refactor dockerfiles to use multi-stage
pravega/gstreamer-pravega pull request #10
Opened 2021-04-28 19:28 UTC by jdmaguire

We have a lot of dockerfiles, there are some issues:

- The name format is irregular. Normal Dockerfile name format is either `(<name>.)Dockerfile` or `Dockerfile(.<name>)` whereas we are doing `Dockerfile-<name>`. It isn't consistent even with other dockerfiles in this repo.
- We have a lot of dockerfiles where Dockerfile 2 relies on Dockerfile 1. Say for files. The normal way one would do this would be a multi-stage dockerfile. Instead we have multiple files and have bash doing the work of building one, then supplying the name to the next step.

This PR reorganizes the docker files. Seven dockerfiles into two dockerfiles. A few dozen lines of bash code removed by letting docker do more lifting.

This doesn't improve build speed but I feel makes it easier to read what is being built & will make it easier to later increase speed.

2021-04-28 21:04 UTC, claudiofahey requested changes
Thanks for cleaning this up. I just have some minor feedback.

2021-04-29 00:59 UTC, jdmaguire commented on pravega-video-server/src/main.rs
> +        .expect("creating config ok");
Was testing something. Didn't mean to push.

2021-04-29 01:00 UTC, jdmaguire commented
The push-release.sh needs some editing

2021-04-29 14:28 UTC, claudiofahey commented
> The push-release.sh needs some editing

You can delete it. We don't use this file. Note I took most of the Docker files from https://github.com/restreamio/docker-gstreamer. That is why there are unused files.

2021-04-29 16:46 UTC, jdmaguire commented on docker/build-release.sh
> +#CARGO_TARGET_DIR environment /cache/build/rust
Ignore. Accidentally committed ;) it is a supprise for another time.

2021-04-29 16:46 UTC, jdmaguire commented on docker/build-release.sh
> +#CARGO_TARGET_DIR environment /cache/build/rust
(Will remove for this PR.)

2021-04-29 17:51 UTC, jdmaguire commented on docker/build-latest.sh
The `push-release.sh` relies on the images built here I believe?

2021-04-29 19:18 UTC, claudiofahey approved these changes

2021-04-29 19:18 UTC, merged