Issue 161: Add scripts for reading and writing MP4 files from/to Pravega
pravega/gstreamer-pravega pull request #162
Opened 2023-06-21 17:01 UTC by RaulGracia

**Change log description**
Added scripts to read/write MP4 files from/to Pravega.

**Purpose of the change**
Fixes #161.

**How to verify it**
Run Pravega in standalone mode and write and read an MP4 file from Pravega.

2023-06-25 07:12 UTC, vangork requested changes

2023-06-25 07:12 UTC, vangork commented on scripts/mp4-file-to-pravega.sh
> +  seal=false sync=false timestamp-mode=tai
Please end the file with a LF.

2023-06-25 07:12 UTC, vangork commented on scripts/mp4-pravega-to-screen.sh
> +! autovideosink sync=true
Please end the file with a LF.

2023-07-12 10:39 UTC, RaulGracia commented on scripts/mp4-file-to-pravega.sh
> +  seal=false sync=false timestamp-mode=tai
Added blank line at the end.

2023-07-12 10:39 UTC, RaulGracia commented on scripts/mp4-pravega-to-screen.sh
> +! autovideosink sync=true
Added blank line at the end.

2023-07-12 10:40 UTC, RaulGracia commented
@vangork thanks for the feedback. As we discussed, I have added 2 versions of the script that writes an MP4 file to Pravega, depending on the mux option. Thanks.

2023-08-03 12:50 UTC, vangork commented
Looks good!

2023-08-03 12:52 UTC, vangork commented
Please sign all the commits and merge.

2023-08-16 08:41 UTC, merged